lab1: tcpserver.c tcpklijent.c
	cc -Wall tcpserver.c -w -o tcpserver
	cc -Wall tcpklijent.c -o tcpklijent

clean:
	find . -not -name 'tcpserver.c' -not -name 'tcpklijent.c' -not -name 'Makefile' -delete
